Repository NxFerrara/FiberPTS, pull requests merged in 2024-04, with the labels that each got.

#27 Bugfix: Minor Bugfixes Post-Setup Testing
  scripts/paths.sh
  scripts/setup/setup.sh
  src/screen/screen.py
  src/utils/paths.py
  templates/detect_display_errors.service
  templates/init_display.service
  templates/screen.service
  templates/touch_sensor.service
Labels: improvement

#32 Setup Timezone
  scripts/setup/setup.sh
Labels: feature

#30 Bugfix/pipe reading
  config/logging.conf
  src/cloud_db/cloud_db.py
  src/screen/screen.py
  src/touch_sensor/touch_sensor.py
  src/utils/screen_utils.py
  src/utils/utils.py
Labels: bug

#34 Add TIMEZONE configuration
  config/config.sh
  scripts/setup/setup.sh
Labels: refactor

#39 Add popup limit for invalid taps
  config/screen_config.py
  src/screen/screen.py
Labels: bug

#40 Fix shutdown checking process
  scripts/run/shutdown.sh
Labels: bug

#37 Refactor source files
  src/cloud_db/cloud_db.py
  src/screen/screen.py
  src/touch_sensor/touch_sensor.py
  src/utils/paths.py
  src/utils/screen_utils.py
  src/utils/touch_sensor_utils.py
  src/utils/utils.py
Labels: refactor

#45 Create README.md
  README.md
Labels: documentation
